version: '3.3'
services:
  redis:
    image: redis
    restart: unless-stopped
  laravel:
    build: './back-end'
    restart: unless-stopped
    volumes:
      - ./back-end/src:/var/www
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: testing
      POSTGRES_USER: fittie
      POSTGRES_DB: fittie
  nginx:
    image: nginx:latest
    ports:
      - "8223:443"
    volumes:
      - ./back-end/src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl/cert.pem:/etc/nginx/conf.d/cert.pem
      - ./nginx/ssl/key.pem:/etc/nginx/conf.d/key.pem
    links:
      - laravel
